management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    stream:
      bindings:
        test-data-created:
          destination: test-data-created
