apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  finalizers:
  - resourceclaims.services.apps.tanzu.vmware.com/finalizer
  name: mysql-1
  namespace: demo-team
spec:
  ref:
    apiVersion: with.sql.tanzu.vmware.com/v1
    kind: MySQL
    name: mysql-1
    namespace: service-instances
