apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-demo-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-demo-app
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/p-ssanders/tap-demo-app
      ref:
        branch: main
  serviceClaims:
    - name: mysql
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: mysql-1-demo-team
    - name: rabbitmq
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: rmq-1-demo-team